import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar'
import { NotesContextProvider } from '@/context/NoteContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotesContextProvider>
            <Navbar />
        {children}
        </NotesContextProvider>
        </body>
    </html>
  )
}
